# Generated by Django 3.1.5 on 2021-01-08 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgeting', '0003_auto_20201230_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetitem',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='income',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
