# Generated by Django 3.1.5 on 2021-02-05 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budgeting', '0004_auto_20210107_1937'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('notes', models.TextField(blank=True, default='', null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='budgetitem',
            old_name='description',
            new_name='notes',
        ),
        migrations.RemoveField(
            model_name='budgetitem',
            name='time_period',
        ),
        migrations.AddField(
            model_name='budgetitem',
            name='parent_budget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budgeting.budget'),
            preserve_default=False,
        ),
    ]
