# Generated by Django 3.1.5 on 2021-02-18 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgeting', '0006_budgetitem_spent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetitem',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='income',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
